name: json_web_token
version: 0.1.3
author: Alexandre Maurel <alexandre.maurel@gmail.com>
description: Json Web Token
homepage: https://github.com/amaurel/json_web_token
documentation: https://github.com/amaurel/json_web_token
dependencies:
  cipher: any
  crypto: any
  rsa_pkcs: any
dev_dependencies:
  unittest: any
