name: json_web_token
version: 0.1.3
author: Alexandre Maurel <alexandre.maurel@gmail.com>
description: Json Web Token
homepage: https://github.com/amaurel/json_web_token
documentation: https://github.com/amaurel/json_web_token
dependencies:
  cipher: ">=0.7.0 <0.8.0"
  crypto: ">=0.9.0 <0.10.0"
  rsa_pkcs: ">=0.1.1 <0.2.0"
dev_dependencies:
  unittest: any
